Uninett/Argus-frontend

src/components/header/Header.tsx
src/handleFeide.tsx
src/protected.route.tsx
src/views/loginView/LoginView.tsx

Also uses hooks to update name in header.
Both local login and feide performs as expected, no logout for feide yet.

:sparkles:Feide login fully functional

---

src/components/react-table/Table.tsx

Should wait until https://github.com/ddabble/aas/pull/11 is merged.

Fix alerts URL and expected JSON format

---

src/components/filterBuilder/filterBuilder.tsx

move error dialog from then to catch

fix bad request dialog

---

.gitignore
public/config/config.example.js
public/config/config.js
public/index.html
src/components/filterBuilder/filterBuilder.tsx
src/components/profile/Profile.tsx
src/components/profileList/ProfileList.tsx
src/views/alertView/AlertView.tsx
src/views/loginView/LoginView.tsx

The back-end location can be configured in the config.js file.

Add support for configuring where the front-end finds the back-end.

---

README.md
src/components/filterBuilder/filterBuilder.tsx

Requires having merged Uninett/aas#56.

API update - Rename networkSystem to alertSource

---

package-lock.json
package.json
src/api/hooks.tsx
src/api/index.tsx
src/components/actiondialog/ActionDialog.tsx
src/components/alertspreview/AlertsPreview.tsx
src/components/dialogue/Dialogue.tsx
src/components/filterbuilder/FilterBuilder.tsx
src/components/profile/Profile.tsx
src/components/profilelist/ProfileList.tsx
src/components/selector/index.tsx
src/components/snackbar/index.tsx
src/components/timeintervals/TimeIntervals.tsx
src/components/timeintervalselector/TimeIntervalSelector.tsx
src/components/timeslot/Timeslot.tsx
src/constants.ts
src/protected.route.tsx
src/serviceWorker.ts
src/store.tsx
src/utils.tsx
src/views/alert/AlertView.tsx
src/views/filters/FiltersView.tsx
src/views/login/LoginView.tsx

1. Create hooks for managing state from API
I'm unsure if this was a good decision or not
but it makes the code more declarative.
2. Rewrite/refactor ProfileView and Profile component
Previously it seemed to barely be working, and relied
on some unconventional "hacks" or undefined behaviour.
Now it's hopefully (TM) better...
3. Refactoring, creation of utility functions, split into
new components and more
Created a custom selector component as well as
an ActionDialog component.

Refactor, create hooks, fix Timeslots view and more

---

src/api/index.tsx

See https://github.com/Uninett/Argus/issues/140

Make the first day of the week be number 1

---

src/views/filters/FiltersView.tsx

When refactoring the filters view I somehow removed the header...

Add back missing header from FiltersView

---

src/api/index.tsx

Depends on https://github.com/Uninett/Argus/pull/142 in backend.

Use ticket url endpoint for updating ticket url

---

src/api/index.tsx
src/components/incident/IncidentDetails.tsx
src/components/incidenttable/IncidentTable.tsx
src/components/profile/Profile.css
src/components/profile/Profile.tsx
src/components/profilelist/ProfileList.tsx
src/components/sourceselector/index.tsx
src/components/tagselector/index.tsx
src/views/incident/IncidentView.tsx

Improve incidentsview (use query params, ui improvements), add phone number selector to profiles view, fix acks and more

Feat phone and query fixes

---

src/components/incidenttable/IncidentTable.tsx

Hide blue ticket button

---

src/components/incidenttable/IncidentTable.tsx

Hide incident multiselect and its actions

---

src/components/incidenttable/IncidentTable.tsx

Remove id-column in incident table

---

src/components/incident/IncidentDetails.tsx
src/components/incident/SignedMessage.tsx
src/components/incidenttable/IncidentTable.tsx
src/utils.tsx

I *think* this is all cases where a full timestamp is shown.
Closes #126.

Show all timestamps with the same format

---

src/api/index.tsx
src/components/profilelist/ProfileList.tsx

Polish: Remove mentions of Slack

---

src/components/incident/IncidentDetails.tsx

Stop showing empty ticket url as error

---

src/api/hooks.tsx
src/api/index.tsx
src/components/incidenttable/IncidentTable.tsx
src/utils.tsx
src/views/incident/IncidentView.tsx

Implement support for the new incidents backend API that uses cursor pagination.

Implement cursor pagination

---

src/components/incident/IncidentDetails.tsx
src/utils.tsx

This closes Uninett/Argus-frontend#151

Show duration in details for stateful incidents

---

README.md

I updated the README while trying out Argus-frontend for the first time.
I restructured the headlines for better readability, rephrased sentences, and added some information where necessary.
The changes intend to enhance clarity for the unfamiliar user, while hopefully preserving the main contents.

README: update structure and wording

---

src/api/index.tsx
src/components/filterbuilder/FilterBuilder.tsx
src/components/filters/contexts.ts
src/components/incidenttable/FilteredIncidentTable.css
src/components/incidenttable/FilteredIncidentTable.tsx
src/components/incidenttable/IncidentTable.tsx
src/components/sourceselector/index.tsx
src/components/tagselector/index.tsx
src/config.tsx
src/utils.tsx
src/views/filters/FiltersView.tsx
src/views/incident/IncidentView.tsx

This patch introduces fixes to the filter view. It
updates it to work correctly with the changes in the API
and also adds functionality for editing existing filters.
All in all this patch seems to work quite well, with
snackbar alerts used to provide the user with feedback.
Doesn't look that good, but does the job.

Fix and improve filters view

---

src/components/timeslot/index.tsx
src/components/timeslotlist/index.tsx

UX improvements by
- switching from AutoComplete component to Select component
- aligning subcomponents by using Grid's
- disable components on update

Switch to Select component in timeslots

---

src/views/filters/FiltersView.tsx
src/views/incident/IncidentView.tsx

Fix to which source chosen not shown in source filter box

---

.dockerignore
Dockerfile
README.md
docker-compose.yml
docker-entrypoint.sh
docker/api/Dockerfile
docker/api/docker-entrypoint.sh
package.json
src/config.tsx

This add a full Docker Compose-based environment for Argus frontend development, which includes a full backend setup to work against.
Some tweaks and bugfixes are included, as they were blocking the completion of the PR.

Add a complete Docker Compose-based development environment

---

src/components/phonenumber/index.tsx

Fix mistake in confirm message for deleting a phone number

---

src/components/header/Header.tsx
src/components/incident/styles.tsx
src/components/incidenttable/IncidentTable.tsx
src/components/menu/index.tsx
src/components/modal/Modal.tsx
src/utils.tsx

Can be merged on it's own, but preferably after #187

Create new Incident Modal and add "copy-canonical-url" to incident details modal

---

src/components/buttons/OutlinedButton.tsx
src/components/login/Login.tsx
src/components/textfields/OutlinedTextField.tsx
src/views/login/LoginView.tsx

This isn't the best designed login view, but this is a lot better as a base to build a new and nicer one than the previous.

Redesign login view and split it into components

---

src/components/header/Header.tsx
src/components/incidenttable/IncidentTable.tsx

- Reduce size of header and set overflow to hidden
- Remove the annoying "realtime" text that's displayed when realtime is enabled

Misc UI changes

---

src/services/RealtimeService.ts

Bugfix realtime this connect

---

src/components/TimePicker.tsx
src/components/timeslot/index.tsx
src/config.tsx

Make time pickers default to be 24h instead of ampm

---

src/api/hooks.tsx
src/api/index.tsx
src/components/incident/IncidentFilterToolbar.tsx
src/components/incidenttable/FilteredIncidentTable.tsx
src/contexts.tsx
src/index.tsx
src/reducers/common.tsx
src/reducers/filter.tsx
src/views/filters/FiltersView.tsx
src/views/incident/IncidentView.tsx

Add functionality for using predefined filters in incident filter toolbar

---

src/components/login/Login.tsx

Make text colors in the Login form white

---

src/components/header/Header.tsx
src/components/login/Login.tsx
src/contexts.tsx
src/protected.route.tsx
src/reducers/common.tsx
src/reducers/filter.tsx
src/reducers/user.tsx

This PR adds information about the user to the global app context, and replaces some (not all) uses of user information with this. 
Closes #199

Keep track of user in global app context

---

src/api/actions.tsx
src/components/alertsnackbar/index.tsx
src/components/buttons/OutlinedButton.tsx
src/components/filteredincidentprovider.tsx
src/components/incident/CreateAckSignOffAction.tsx
src/components/incident/IncidentDetails.tsx
src/components/incident/IncidentFilterToolbar.tsx
src/components/incident/ManualCloseSignOffAction.tsx
src/components/incident/SignOffAction.tsx
src/components/incident/styles.tsx
src/components/incidentsprovider.tsx
src/components/incidenttable/FilteredIncidentTable.tsx
src/components/incidenttable/IncidentTable.tsx
src/components/incidenttable/IncidentTableToolbar.tsx
src/components/incidenttable/RealtimeIncidentTable.tsx
src/services/RealtimeService.ts
src/views/incident/IncidentDetailView.tsx
src/views/incident/IncidentView.tsx

This PR (draft) does the following:
1. It improves on the RealtimeService, such that the components has better access to state.
2. It adds a better way of dealing with frontend filtering, and shares it between the realtime incident component and the interval incident component.
3. Fixes some useEffect's, that previously didn't handle dependencies correctly
As is tradition, this needs to be rebased when the other PRs are merged.

Realtime improvements & upgrade of table

---

src/App.tsx
src/api/index.tsx

Display alert when error code 5XX is recieved

---

src/api/actions.tsx
src/components/incident/AddTicketUrlSignOffAction.tsx
src/components/incident/SignOffAction.tsx
src/components/incident/test/AddTicketUrlSignOffAction.test.tsx
src/components/incidentsprovider.tsx
src/components/incidenttable/IncidentTableToolbar.tsx
src/components/incidenttable/test/IncidentTableToolbar.test.tsx

Adds "Add Ticket" button for bulk adding ticket url to selected incidents. Tests implemented functionality. Closes #265

Add ticket url bulk

---

src/components/incidenttable/IncidentTableToolbar.tsx

Shows success/error snackbars on all bulk operations on incidents

---

src/components/incident/IncidentFilterToolbar.tsx
src/components/incidenttable/FilteredIncidentTable.tsx
src/components/incidenttable/RealtimeIncidentTable.tsx
src/components/profilelist/ProfileList.tsx

Fix bug: frontend crashes when backend is offline

---

src/components/timeslot/index.tsx

Reset save- and delete button loading state after api call

---

src/components/timeslot/index.tsx
src/components/timeslot/timeslot.css
src/components/timeslotlist/index.tsx
src/components/timeslotlist/timeslotlist.css

Make Timeslot-page responsive to different screen sizes

---

package.json
src/config.tsx
src/views/incident/IncidentView.test.tsx
src/views/incident/IncidentView.tsx

- Frontend version is retrieved from package.json
- API version is hardcoded (suggestions for other solutions - ?)
Closes #215

Displays frontend-, backend- and api versions

---

src/components/notificationprofile/AddPhoneNumberDialog.test.tsx
src/components/notificationprofile/NotificationProfileCard.test.tsx
src/components/notificationprofile/NotificationProfileCard.tsx

Tests for AddPhoneNumberDialog- and NotificationProfileCard-components are included in this pull request.
We still need tests for NotificationProfileList as well to cover the entire page, so making this PR a draft for now.
Closes #314 when done.

Write tests for Notification profile page

---

src/components/dialogs/ConfirmDialog.tsx
src/components/incident/IncidentDetails.css
src/components/incident/IncidentDetails.tsx
src/components/incidenttable/IncidentTable.tsx
src/components/incidenttable/IncidentTableToolbar.css
src/components/incidenttable/IncidentTableToolbar.tsx

Make modals and pop-ups responsive to different screen sizes

---

src/components/buttons/ConfirmationButton.tsx
src/components/incident/IncidentDetails.tsx
src/components/incident/ManualCloseSignOffAction.tsx
src/components/incidenttable/FilteredIncidentTable.tsx
src/components/incidenttable/IncidentTable.tsx

Interval update is postponed if user opens incident detail view, or has at least one incident checked.
Closes #323

Make interval update more user friendly

---

README.md

Document REACT_APP_COOKIE_DOMAIN variable

---

CHANGELOG.md
NOTES.md

Fixes #367
Adds release notes and changelog files.
They are pretty much identical rn as there isnt alot to write about

Add release notes and changelogs

---

src/components/sourceselector/index.tsx
src/components/tagselector/index.tsx
src/state/reducers/timeframe.tsx
src/utils.tsx

Polish switch-statements in accordance with _Argus code audit_ [July 2022] by GÉANT.
Closes #395

Remove/replace switch-statements with too few case-clauses

---

src/api/actions.tsx
src/api/client.ts
src/components/alertsnackbar/index.tsx
src/components/apiinterceptor.tsx
src/components/filteredincidentprovider.tsx
src/components/filterprovider.tsx
src/components/incident/IncidentDetails.tsx
src/components/incidentsprovider.tsx
src/components/incidenttable/FilteredIncidentTable.tsx
src/components/incidenttable/RealtimeIncidentTable.tsx
src/components/table/Table.tsx
src/components/tagselector/index.tsx
src/components/timeslotdayselector/index.tsx
src/services/RealtimeService.ts

Remove commented out code as suggested in _Argus code audit_ [July 2022] by GÉANT.
Closes #394

Remove commented out code

---

src/api/client.ts
src/api/hooks.tsx
src/components/filterprovider.tsx
src/components/incident/IncidentDetails.tsx
src/components/incident/IncidentFilterToolbar.tsx
src/components/incidenttable/IncidentTable.tsx
src/components/notificationprofile/NotificationProfileCard.test.tsx
src/components/notificationprofile/NotificationProfileCard.tsx
src/components/notificationprofile/NotificationProfileList.tsx
src/components/selector/index.tsx
src/components/timeslotlist/index.test.tsx
src/components/timeslotlist/index.tsx
src/services/RealtimeService.ts
src/utils.tsx
src/views/incident/IncidentDetailView.tsx
src/views/incident/IncidentView.test.tsx
src/views/incident/IncidentView.tsx

Go through unfinished code as suggested in _Argus code audit_ [July 2022] by GÉANT.
Closes #393

Remove todo comments, or implement changes as suggested in comments

---

CHANGELOG.md
NOTES.md
src/components/incident/IncidentDetails.tsx

Flip incident events order

---

CHANGELOG.md
NOTES.md
src/components/incident/IncidentFilterToolbar.tsx

Reword "Max level" to "Max severity level"

---

src/api/actions.tsx
src/api/client.ts
src/api/types.d.ts
src/components/incident/CreateAckSignOffAction.tsx
src/views/incident/IncidentView.test.tsx

Use bulk endpoints for bulk operations

---

src/api/types.d.ts
src/components/incident/CreateAckSignOffAction.tsx

Bugfix
description inside EventBody is for api v1 and description outside EventBody is for api v2

Add description to acknowledment body

---

CHANGELOG.md
NOTES.md
src/components/destinations/DestinationGroup.tsx
src/components/notificationprofile/NotificationProfileList.tsx

Fix destinations fetch in notification profiles
