Uninett/Argus-frontend

.eslintrc.js
.prettierrc.js
package-lock.json
package.json

The README states that this project uses prettier to format all typescript code, but the default prettier configuration does not match the formatting style used thus far. This PR matches better than the default configuration.
Based on (but modified slightly): https://www.robertcooper.me/using-eslint-and-prettier-in-a-typescript-project

Create eslint and prettier configuration for TS

---

.eslintrc.js
package-lock.json
package.json
src/api/index.tsx
src/auth.tsx
src/components/header/Header.tsx
src/components/incident/Chips.tsx
src/components/incident/IncidentDetails.tsx
src/components/incident/SignOffAction.tsx
src/components/incident/SignedMessage.tsx
src/components/incident/styles.tsx
src/components/incidenttable/IncidentTable.tsx
src/config.tsx
src/utils.tsx
src/views/incident/IncidentView.tsx
src/views/login/LoginView.tsx

This PR achieves the following:
- Replace list/table component for active/open incidents with one from material ui
- Updates to work with latest master branch of backend (Uninett/Argus 137193932913d103fba6e0ded982702bf4a1b12d)
Incident overview features:

Implement support for realtime API and change to better table component

---

src/api/hooks.tsx
src/api/index.tsx
src/components/incident/IncidentDetails.tsx
src/components/incidenttable/IncidentTable.tsx
src/utils.tsx
src/views/incident/IncidentView.tsx

Incident details modal:
- Fetches acknowledgements and other  related events from Argus API
- Displays the acks and events in a nice list
- The "Create acknowledgement" button now will actually create an acknowledgement.
Tag filtering:
- Tags of the same "type" (same key) works
as an OR, meaning that if the following
tags are used:
host=testhost1, host=testhost2
Incidents with either the tag "host=testhost1"
or the tag "host=testhost2" will be shown,
but all other values for host will be filtered
out.
- Tags of different "types" works as an AND,
meaning that if the following tags are used:
host=testhost1, host=testhost2,
ticket_url=http://tr.t/123
Only the incidents with host in (testhost1, testhost2)
AND with ticket_url equal to http://tr.t/123
will be displayed.

Display events, acknowledgements and tags & proper filtering based on tags

---

src/api/index.tsx
src/components/incidenttable/IncidentTable.tsx
src/views/incident/IncidentView.tsx

This now makes it possible to conditionally display the acknowledged incidents, but will by default only display open+unacknowledged incidents.
When the "open" option for "show open/closed" is used it will use the "open+unacked" endpoint when this checkbox option is disabled. When it is enabled it will use the "open" endpoint.

Implement "show acked incidents" checkbox for incident view

---

src/components/incidenttable/IncidentTable.tsx
src/utils.tsx

Closes #121 
It's a little odd that this part of the details box is defined in the incident table, not the incident detail box itself. Not something we should bother to fix before 1.0 though.
@lunkwill42, I've tagged you because exactly what we ought to have as the title of the box is very much up for discussion. It's very easy to change though, as long as only things stored directly on the incident are used.

Improve title of incident detail box

---

src/components/incident/IncidentDetails.tsx

Closes #143, independently of what the backend does.
Closes #125 as well.
An empty details_url field is shown by an en dash in the UI.

Only linkify details_url if absolute

---

src/components/incidenttable/IncidentTable.tsx

Realtime updates are not working in v1.0.0 or v1.0.1 - apparently, the frontend is requesting the **wrong** backend URL for realtime updates.

Fix incorrect URL for realtime updates

---

README.md

This adds the missing docs.
Depends on #179, so this will be left in Draft mode until that is merged.

Document the available configuration options

---

src/views/filters/FiltersView.tsx

Somehow the header has been missing form the filters view for some time now. This just adds it back like the other views does it at the current HEAD.
Closes #172

Add missing header to FiltersView

---

src/App.tsx
src/api/index.tsx
src/components/incident/IncidentFilterToolbar.tsx
src/components/incidenttable/IncidentTable.tsx
src/views/filters/FiltersView.tsx
src/views/incident/IncidentDetailView.tsx
src/views/incident/IncidentView.tsx
src/views/notificationprofile/NotificationProfileView.tsx
src/views/settings/SettingsView.tsx
src/views/timeslot/TimeslotView.tsx

This PR implements the required functionality of #148.
It includes the following:
This required refactoring of <Header/> component usage. 
Closes #148

Add route for showing incident by canonical url

---

src/components/incident/IncidentFilterToolbar.tsx
src/components/incidenttable/FilteredIncidentTable.tsx
src/components/tagselector/index.tsx
src/views/filters/FiltersView.tsx
src/views/incident/IncidentView.tsx

This PR includes some minor improvements to the incidents filter toolbar (rewriting to remove use of Grid), as well as introducing a drop-down that is supposed to be used for useful filter settings that are not needed to be visible at all times.
Currently the only setting in this drop-down is the auto update setting, but there will probably be use for it.
The previous PRs should be merged before this one.

Minor improvements to incidents toolbar, new feature of an drop-down with additional setting 

---

src/components/timeslot/index.tsx
src/components/timeslotlist/index.tsx
src/views/timeslot/TimeslotView.tsx

This patch does the following:
1. Change from using Grid components to using custom flexbox using
styled components.
This made it easier to position the UI elements the way I wanted.
2. Add border to the timeslot recurrence.
Doing this makes it easier to differentiate between the timeslot
recurrences.
3. Move the "remove recurrence" button to the upper right corner

Add border to timeslot recurrence and Timeslot UI improvements

---

src/components/incident/styles.tsx
src/components/incidenttable/IncidentTable.tsx
src/services/RealtimeService.ts

This PR tries to improve the realtime integration in Argus:
1. Seperate out the Websockets logic from incidents table to a seperate service class. 
2. Make incidents that are updated (by user modification or by realtime update) stay visible for 5 seconds before they disappear IF they are supposed to disappear. --- some exceptions that needs to be fixed.
3. Add border to the left-side of the with a color representing the state
Relies on previous PRs, at least #191.

Feat better realtime integration & UI changes

---

src/api/actions.tsx
src/contexts.tsx

This PR introduces the useFilters hook that is an easy and clean way to give components access to the filters, and ability to act on them such that any updates are passed to all other components using the global state.

Create useFilters hook

---

src/App.tsx
src/components/alertsnackbar/index.tsx

This PR introduces the useAlerts() hook that can be used anywhere in the app for creating alerts.

Create useAlerts hook and use context in App for alerts snackbar

---

src/api/actions.tsx
src/components/incident/IncidentFilterToolbar.tsx
src/components/incident/styles.tsx
src/components/incidentsprovider.tsx
src/components/incidenttable/IncidentTable.tsx
src/components/incidenttable/RealtimeIncidentTable.tsx
src/services/RealtimeService.ts
src/views/incident/IncidentView.tsx

This PR works on the realtime features. It switches to using contexts for sharing state, and adds some fixes to the RealtimeService, as well as properly handling switching between realtime/interval. +++
Closes #201
Closes #200 
Closes #217
Interacts with #209 by making the decision to not use paging (it's just removed for now). This can probably be undone, because the improved internal architecture makes such changes easier. 
This PR requires rebasing, but because the # of PRs keep increasing I will not spend time doing that everytime I change something. This is based on all previous PRs, even those that are not merged.
NOTE: Not infinitely loading yet, but will be added

Feat realtime list

---

src/components/filterprovider.tsx
src/components/incident/IncidentFilterToolbar.tsx
src/components/incidenttable/FilteredIncidentTable.tsx
src/localstorageconsts.ts
src/utils.tsx

This PR introduces features that allow for persistence of values in localStorage. It does this by copying parts of contexts/states on every change to them, and then attempting to load from localstorage on initialization. 
Currently implements storage of the following:
1. Page size (for Interval)
2. Selected filter (including open/closed, acked/unacked, and If realtime/interval/never is selected).
It also stores a timestamp along side with the data, which might come in useful during eventual debugging or future improvements.

Feat keep preferences in localstorage

---

docker-compose.yml

Because:
- The docker-compose config is for development environments.
- There is no need for automatic restarting of containers in a dev env.
- This causes manuallt stopped containers to restart whenever the Docker  daemon is restarted (e.g on every reboot)

Remove docker-compose restart directives

---

src/components/incident/SignedMessage.tsx

Replaces Date() constructor with date-fns' parseISO(). This solution is chosen over converting an invalid timestamp string into a valid one, since the latter involves a more complex refactoring and is less 'universal' in implementation.

Fix invalid time bug in Safari

---

src/components/incident/IncidentDetails.tsx

The user can now type directly into the ticket field without clicking a button first.

Remove the ticket url edit button.

---

src/components/incidenttable/IncidentTableToolbar.tsx

When bulk ack or close/re-open is successfully completed, affected incidents are deselected and multi-action bar disappears. Closes #242

Fixes issue #242

---

src/api/client.ts
src/api/consts.ts
src/api/types.d.ts
src/colorscheme.tsx
src/components/filterprovider.tsx
src/components/incident/Chips.tsx
src/components/incident/IncidentDetails.tsx
src/components/incident/IncidentFilterToolbar.tsx
src/components/incidenttable/IncidentTable.tsx

The frontend now shows the severity level for each incident, both in the incident list and in the details dialog. The names and colors of the severity levels is only a suggestion, and can easily be changed later.
Here are some screenshots of the changes that has been made:

Incident severity levels

---

src/api/client.ts
src/api/utils.ts

Error cause is now shown to user in JSON format. Not the prettiest solution, but definitely the simplest one to implement. Showing cause string directly involves going in a rabbit hole of checking each endpoint, and writing "adapter"-code on frontend.
Closes #124

Shows error cause to user

---

src/components/header/Header.tsx

The navbar will now be shown as a dropdown list on smaller devices:
The menu icon in the top left corner can be used to toggle the visibility of the dropdown menu. Other than that, the functionality is pretty much the same as for the original navbar.
To see the navbar as seen on a mobile device the "Toggle device toolbar" in Chrome can be used (top left corner of the developer tools window).

Implement mobile friendly dropdown navbar

---

src/components/timeslot/index.test.tsx
src/components/timeslot/index.tsx
src/components/timeslotlist/index.test.tsx

- Timeslot name is required in order to make a request to server
- Start time is required in order to make a request to server (unless "All day" is checked)
- End time is required in order to make a request to server (unless "All day" is checked)
- Start time must be before end time in order to make a request to server (unless "All day" is checked)
- Checking "All day" drops all time related restrictions mentioned above
- All required fields are marked with asterisk.
- If provided timeslot name is a blank string, the input field is highlighted in red and helper text appears. 
- If provided start-/end time is left blank, the input field is highlighted in red,  helper text "Required" appears, Save-button is disabled. 
- If provided start-/end time is incomplete, the input field is …

Correctly marks required fields on the Timeslot-page

---

README.md

.. currently: how to get rid of a warning about too many watchers that
might prevent tests from running.

Add tips-section for dev on linux

---

src/api/client.ts
src/api/types.d.ts
src/components/filteredincidentprovider.tsx
src/components/filterprovider.tsx
src/components/incident/IncidentFilterToolbar.tsx
src/components/incidenttable/FilteredIncidentTable.tsx
src/components/tagselector/index.tsx
src/views/incident/IncidentView.test.tsx

**Changes made:**
- Tags and Sources are moved to FilterContent. This is both mirroring how backend recognizes filters, as well as facilitates state's recognition of _any_ changes to the filter params. 
- State is now reactive to _any_  valid updates to the sources and tags inputs, and sends a request to the backend on _any_  valid update. Previously, updates to tags and/or sources in the filter toolbar were not triggering requests to the backend, and incidents not matching those updates were "removed" from the table on frontend (but they still occupied space).
- Invalid source- and tag formats provided by the user are silently ignored (they are removed from the input fields and do not trigger table update). Previously, the invalid formats were added to the input field and were triggering …

Fix incidents table filtering

---

src/components/incident/Chips.tsx
src/views/incident/IncidentView.test.tsx

Chip elements are updated to match the button in the filter toolbar:
Unsure whether labelling in the detailed view should also be updated from "Unacknowledged" to "Unacked"..?
Closes #333

Fix inconsistent labeling

---

docker-compose.yml
docker/api/Dockerfile

Mostly this is about the first commit:
Using `${UID}` as the `user` value in `docker-compose.yml` causes problems on macOS (where the mapping/privilege issues don't apply anyway). However, it seems setting it to something other than the image default of `node` might cause problems for the latest node images from Dockerhub (npm just exits with code `243`, producing no output or logs to indicate what went wrong).

Make docker compose build more flexible

---

src/api/client.ts

Incidents page blanked out (or certain fields did not display filter changes) when a user selected an existing filter. This is due to _Filter_ object changes introduced in #346. 
Fields _sourceSytemIds_ and _tags_ in the _Filter_ object are populated from the _filter string_. 
Closes #349

Fix blank page due to selecting an old-style filter

---

docker-compose.yml
docker/api/Dockerfile
docker/api/dockerdev.py

This introduces a custom settings file for the API backend service container, so some of the more complex settings of the API server can be manipulated while testing/developing the frontend.
The default settings file used will enable the SMS-as-email plugin, so that developers will be able to work with dumps of production data that contain profiles with phone numbers in them (the API server will crash if there are SMS-enabled profiles present in the database when no SMS plugin is enabled in the settings).

Enable the SMS media plugin in docker-compose env

---

.github/workflows/sonarqube.yml

We were hit by kitabisa/sonarqube-action#34 - which broke our sonarqube workflow since about July 15 this year.

Upgrade sonarqube-action to v1.2.0

---

CHANGELOG.md
src/components/incident/SignedMessage.tsx

Timestamps in the _Related events_ feed display seconds now.
Closes #370

Display seconds in all timestamps of the detailed incident view

---

CHANGELOG.md
src/components/phonenumber/index.tsx

Fixes #434 
Updates  css for the phonenumber component.
Vertically aligns buttons, adds margins and evenly spaces the buttons out inside the paper.
Removes CSS that either wasnt used or didnt do anything.

Make phonenumber component prettier

---

CHANGELOG.md
src/components/timeslot/index.tsx

Fixes #435.
Based on this discussion from the MUI repo: https://github.com/mui/material-ui/issues/19977

Make day select menu stay still

---

CHANGELOG.md
src/components/phonenumber/index.tsx

Previosuly the button worked by having an OnClick event. But at the same time the form still seemed to have a submit event
that triggered when you press enter inside the form, and the default behaviour is to refresh the page.
This fix puts the OnClick logicinside a OnSubmit handler instead, while disabling the default submit behaviour (stops the page from rereshing). This makes it so
pressing enter and clicking the save/create button behaves the same way- They should both behave the same as the old behaviour for clicking the button.
Fixes #433

Fix enter button not saving/updating telephone number

---

CHANGELOG.md
NOTES.md
src/components/notificationprofile/NotificationProfileCard.test.tsx
src/components/notificationprofile/NotificationProfileCard.tsx
src/components/notificationprofile/NotificationProfileList.tsx

- Added option "None" to the _Phone Number selector_ in notification profiles.
- Made option "None" a default one when creating a new notification profile.
Closes #404

Make phone number optional when creating a notification profile

---

CHANGELOG.md
src/components/incident/CreateAckSignOffAction.tsx
src/components/incident/IncidentDetails.tsx
src/components/incident/ManualCloseSignOffAction.tsx
src/components/incidenttable/IncidentTableToolbar.tsx

Fixes parts of #423 
also removes some trailing whitespace
Uses spread operator to only override the text if multiple incidents are selected. Is this a clean way to do it?

Use plural words when bulk operating multiple incidents

---

.github/workflows/docker-images.yml
docker/Dockerfile
docker/README.md

To implement Uninett/argus-docker#1 in a more fluent way, production-oriented Docker images of the back-end and front-end components should be built and published as packages attached to each of the source repositories.
This adds a Dockerfile to produce a production oriented image of the front-end UI application, and sets up a GitHub Actions workflow to build and publish said image as a *package* on every release made from this repo.
Because of how the site configuration is compiled in the statically generated application files, this image is just a stage 1 build image, so documentation on how to use it is added to a `README.md` file.

Build and publish production-oriented builder Docker image as GitHub package

---

src/api/client.ts
src/api/types.d.ts
src/state/contexts.tsx
src/state/hooks.tsx
src/state/reducers/destinations.ts

Global state for destinations is needed since destinations data will be used in both destinations settings components, and notification profiles components. 
This PR offers no functional changes, just a preparation for adding destinations to Argus

Add global state logic and API calls for destinations

---

CHANGELOG.md
NOTES.md
src/api/client.ts
src/api/types.d.ts
src/components/notificationprofile/NotificationProfileCard.test.tsx
src/components/notificationprofile/NotificationProfileCard.tsx
src/components/notificationprofile/NotificationProfileList.test.tsx
src/components/notificationprofile/NotificationProfileList.tsx
src/utils.tsx

- Removed _Media_-selector
- Replaced _Phone number_-selector with _Destinations_-selector
- Notification profiles operate with destinations instead of phone number
- User can now chose **multiple** destinations per notification profile
- Destinations menu items names are either a label (user-given destination name), or a _suggested label_ (set by backend, f.e "SMS: +XXXXXXXXXX"), or an actual settings value (f.e. actual phone number, or email). But on hover event over a destination menu iten, the actual settings value (f.e. actual phone number, or email) will be displayed in a tooltip.
- Destination in the menu have checkboxes and are divided in categories after the media type that destinations belong to.
NB! The _Pluss_-button still opens a create new phone menu instead of a new …

Add destinations to notification profiles

---

CHANGELOG.md
NOTES.md
src/components/alerts/AlertAppbar.test.tsx
src/components/alerts/AlertAppbar.tsx
src/components/apiinterceptor.tsx
src/components/header/Header.tsx
src/components/login/Login.test.tsx
src/components/login/Login.tsx
src/views/login/LoginView.test.tsx
src/views/login/LoginView.tsx

There are now 3 different ways to inform user about errors in _Login view:_
1. Error appbar in case of netwrok/server problems
2. Helper text informing about wrong credentials if userpass request failes
3. Error snackbar in case get user request fails
Closes #451

Improve error handling in Login view

---

.github/workflows/node.js.yml

Also fail if an error happens while uploading coverage.

Use codecov token in uploading coverage

---

.github/workflows/docker-images.yml
.github/workflows/node.js.yml
.github/workflows/sonarqube.yml
.github/workflows/towncrier.yml

Since we don't really use fork to interact with this repository, we don't need to split out the codecov uploading step, but upgrading the Github actions is still good to have.

Update Github actions

---

towncrier.toml

Release 24.7.0 made this necessary by scanning for invalid filenames
References: https://github.com/twisted/towncrier/pull/622, https://towncrier.readthedocs.io/en/stable/release-notes.html#towncrier-24-7-0-2024-07-31

Add gitkeep file to ignored towncrier files

---

changelog.d/591.fixed.md
docker/Dockerfile

This switches the production Docker image to use the nginx-unprivileged image as its base.  The original image would start nginx as root, while nginx itself would drop privileges to the nginx user.
This updated workflow will ensure nothing is started as root at all when the container starts.
Fixes #591

Run nginx completely unprivileged in container
